---
- name: Install and Set Up Docker
  hosts: Client
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Dockers GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable # focal is ubuntu 20.04 LTS
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest

    - name: Install Docker for Python
      pip:
        name: docker

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

