---
- name: Install and configure munin master
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Install munin master and munin node
      ansible.builtin.package:
        name:
          - munin-node
          - munin
      state: present

    - name: Configure munin-node
      ansible.builtin.lineinfile:
        path: /etc/munin/munin-node.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^#?allow .*', line: 'allow ^192\.168\.232\.129$' }
        - { regexp: '^#?host_name .*', line: 'host_name server3' }
        - { regexp: '^#?host .*', line: 'host 192.168.232.133' }
      notify: restart munin services

  handlers:
    - name: restart munin services
      block:
        - name: restart munin-node
          ansible.builtin.service:
            name: munin-node
            state: restarted

        - name: restart munin
          ansible.builtin.service:
            name: munin
            state: restarted
