---
- name: Install and configure munin master
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Install munin master and munin node
      ansible.builtin.package:
        name:
          - munin-node
          - munin
        state: present

    - name: Configure munin-node
      ansible.builtin.lineinfile:
        path: /etc/munin/munin-node.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^#?allow .*', line: 'allow ^192\.168\.232\.134$' }
        - { regexp: '^#?host_name .*', line: 'host_name server4' }
        - { regexp: '^#?host .*', line: 'host 192.168.232.134' }
      notify: restart munin services

    - name: Add local server to munin host file
      ansible.builtin.lineinfile:
        path: /etc/munin/munin.conf
        line: |
          [server4]
              address 192.168.232.134
        insertafter: EOF
      notify: restart munin services
      run_once: true

  handlers:
    - name: restart munin services
      block:
        - name: restart munin-node
          ansible.builtin.service:
            name: munin-node
            state: restarted

        - name: restart munin
          ansible.builtin.service:
            name: munin
            state: restarted
