---
- name: Install syslog-ng with proper configuration on client
  hosts: Client
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Ensure syslog-ng is installed
      ansible.builtin.package:
        name: syslog-ng
        state: present

    - name: Add destination definition to syslog-ng config
      lineinfile:
        path: /etc/syslog-ng/syslog-ng.conf
        insertafter: 'destination d_.*{'
        line: 'destination d_net { tcp("192.168.232.134" port(514) log_fifo_size(1000)); };'
        create: no #Makes it so that if the file does not exist, it does not create a new file

    - name: Add log path to syslog-ng config
      lineinfile:
        path: /etc/syslog-ng/syslog-ng.conf
        insertafter: 'log {'
        line: 'log { source(s_src); destination(d_net); };'
        create: no
      notify: Restart syslog-ng

  handlers:
    - name: Restart syslog-ng
      service:
        name: syslog-ng
        state: restarted

- name: Restart the control server
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Restart the syslog-ng server
      service:
        name: syslog-ng
        state: restarted
